### ISSUE TITLE
myGoogleNet-shave12 ?

### ISSUE THREAD

**Issue by cabelo** [jczaja/test-movidius#1]
Where is myGoogleNet-shave12 file?

**Comment by jczaja** [comment]
This file should be generated using mvNCCompile. To do so:
1) Download caffe's bvlc_googlenet.caffemodel and get from caffe repo corressponding deploy.prototxt
2) Generate NCS graph: mvNCCompile -w bvlc_googlenet.caffemodel deploy.prototxt -o myGoogleNet-shave12

If you have any other NCS graph prepared then change the name of myGoogleNet-shave12 into the name of your graph.
